---
- name: Fetch file from server1 to controller
  hosts: 172.31.23.20
  tasks:
   - name: Fetch file
     fetch:
      src: file2
      dest: /tmp
- name: Copy file to server2
  hosts: 172.31.28.60
  tasks: 
   - name: Copy file
     copy:
      src: /tmp/172.31.23.20/file2
      dest: /home/ubuntu
