---
- name: Setup fo tomcat
  hosts: all
  tasks:
   - block:
      - name: Install tomcat8
        apt:
         name: tomcat8
         state: present
         update_cache: yes
     rescue:
      - name: Isntall tomcat9
        apt:
         name: tomcat9
         state: present
         update_cache: yes
     always:
      - name: Display tomcat success msg
        debug:
         msg: "Tomcat setup is successfull"

