---
- name: Install required s/w for Jenkins
  hosts: jenkins
  tasks:
   - name: Install required s/w
     apt:
      name: "{{item.a}}"
      state: present
      update_cache: "{{item.b}}"
     with_items:
      - {a: openjdk-8-jdk,b: yes}
      - {a: git,b: no}
      - {a: maven,b: no}
   - name: Download jenkins.war
     get_url:
      url: https://get.jenkins.io/war-stable/2.277.2/jenkins.war
      dest: /home/ubuntu
- name: Install tomcat and tomcat-admin
  hosts: servers
  tasks:
   - name: Install tomcat9 and tomcat9-admin
     apt:
      name: "{{item.a}}"
      state: present
      update_cache: "{{item.b}}"
     with_items:
      - {a: tomcat9,b: yes}
      - {a: tomcat9-admin,b: no}
   - name: Copy the tomcat-users.xml file
     copy:
      src: tomcat-users.xml
      dest: /etc/tomcat9
     notify: Restart tomcat9
  handlers:
   - name: Restart tomcat9
     service:
      name: tomcat9
      state: restarted
...
  



